### ISSUE TITLE
 data issue

### ISSUE THREAD

**Issue by ADHI1808** [sauciucrazvan/botanicabay#2]
where the Data is  stored locally in the hive how to see the data

**Comment by sauciucrazvan** [comment]
You can find the file that contains the entire database on your machine, depending on which platform you choose to run the project on.
For Windows, that will be "%USERPROFILE%/Documents" (or "$HOME/Documents/" on Linux). If you're running the app on Android, the database file will be hidden from the user as it uses the function ```getApplicationDocumentsDirectory``` from [path_provider](https://pub.dev/packages/path_provider).

**Comment by sauciucrazvan** [comment]
As this is not an issue, I'll be closing the thread. If you have any further questions, please email me at razvansauciucc@outlook.com or create a [Discussions](https://github.com/sauciucrazvan/botanicabay/discussions) thread. Have a nice day!
